id: I964B9451
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T23:18:31+00:00'
last_modified: '2022-06-07T21:46:32.003343+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30484
  title: རྫོགས་ལྡན་ཆོས་མཆོག་དབུ་མ་གཞན་སྟོང་གི་ཆོས་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    FD98:
      image_group_id: I1KG10308
      title: ''
      total_pages: 332
      order: 1
      base_file: FD98.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
