id: P004296
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W30484
  title: རྫོགས་ལྡན་ཆོས་མཆོག་དབུ་མ་གཞན་སྟོང་གི་ཆོས་སྐོར།
  author: ''
  volumes:
    b2a99925191245138c9a84f0b7bf6953:
      image_group_id: I1KG10308
      title: ''
      volume_number: 1
      total_pages: 332
      base_file: v001.txt
